name:                zipper-extra
version:             0.1.2.1
license:             MIT
category:            Comonads
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Zipper utils that weren't in Control.Comonad.Store.Zipper
description:         Adds some utility functions for and reexports Control.Comonad.Store.Zipper

dependencies:
- base >= 4.7 && < 5
- comonad
- comonad-extras
- exceptions
- split

library:
  source-dirs: src
